openapi: '3.0.0'
info:
  title: ventas
  description: API encargada de resolver la integración con SAP para ventas.
  version: 1.0.0
servers:
  - url: ventas.tarjeta-copec-poc.svc.cluster.local
paths:
  /tarjetas-combustible:
    post:
      tags:
        - Operaciones
      summary: tarjetas-combustible
      operationId: tarjetaCombustible
      description: >-
        Operación que permite la integración con SAP para registrar la venta con
        tarjetas TAE (Tarjeta de Abastecimiento en Empresa) y TCT (Tarjeta Copec
        de Transporte).
      requestBody:
        description: Datos de entrada
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transaccion'
      responses:
        '202':
          description: La solicitud se a recibido correctamente.
        'default':
          description: La solicitud no se a podido procesar por algún problema.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
  /tarjetas-combustible-callback:
    post:
      tags:
        - Operaciones
      summary: tarjetas-combustible-callback
      description: >-
        Operación que permite a SAP responder el resultado del registro de la
        venta  con tarjeta TAE o TCT.
      requestBody:
        description: Datos de entrada
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/estado-transaccion'
      responses:
        '202':
          description: La solicitud se a recibido correctamente.
        'default':
          description: La solicitud no se a podido procesar por algún problema.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
components:
  schemas:
    transaccion:
      properties:
        id:
          type: number
          description: Identificador de la transacción
        solicitante:
          type: string
          description: Código de la persona que solicita la operación
        numero-rollo-voucher:
          type: string
          description: Número de rollo asociado al voucher emitido
        fecha:
          type: string
          description: Fecha de la operación
        hora:
          type: string
          description: Hora de la operación
        validacion-anillo:
          type: string
          description: Estado de la validación del anillo
        condicion-precio:
          type: string
          description: Tipo de acuerdo de precio
        estado-vigencia:
          type: string
          description: Estado de vigencia de la transacción que permite anularla
        firma-electronica:
          type: string
          description: Código de firma electrónica del documento legal
        orden-compra-cliente:
          type: string
          description: Orden de compra de los clientes fiscales
        tarjeta:
          $ref: '#/components/schemas/tarjeta'
        estacion:
          $ref: '#/components/schemas/eds'
        guia-despacho:
          $ref: '#/components/schemas/guia-despacho'
        vehiculo:
          $ref: '#/components/schemas/vehiculo'
        venta:
          $ref: '#/components/schemas/venta'
        entrega:
          $ref: '#/components/schemas/entrega'
    vehiculo:
      properties:
        patente:
          type: string
          description: Patente del vehículo
        odometro:
          type: string
          description: Kilometraje actual del vehículo
        tipo:
          type: string
          description: Tipo de vehículo
        correlativo:
          type: string
          description: Correlativo del vehículo del cliente
    tarjeta:
      properties:
        numero:
          type: string
          description: Número de tarjeta
        tipo:
          type: string
          description: Tipo de tarjeta
    eds:
      properties:
        codigo:
          type: string
          description: Identificador de una estación de servicio
    guia-despacho:
      properties:
        folio:
          type: string
          description: Número de la guía de despacho
    producto:
      properties:
        codigo:
          type: string
          description: Código del producto
        tipo:
          type: string
          description: Tipo del producto
        precio-unitario:
          type: number
          description: Valor unitario del producto
    venta:
      properties:
        detalle:
          type: array
          items:
            $ref: '#/components/schemas/detalle'
        precio-total:
          type: number
          description: Valor total de la venta
    detalle:
      properties:
        producto:
          $ref: '#/components/schemas/producto'
        cantidad:
          type: number
          description: Cantidad vendida del producto
        unidad-de-medida:
          type: string
          description: Unidad con la que se mide el producto
    entrega:
      properties:
        tipo:
          type: string
          description: Tipo de entrega
        descripcion:
          type: string
          description: Descripción del tipo de entrega
        costo-flete:
          type: number
          description: Costo del flete asociado a la operación si corresponde
    estado-transaccion:
      properties:
        id:
          type: number
          description: Identificador de la transacción
        pedido:
          type: string
          description: Numero de pedido con que se registra la transacción en SAP
        posicion:
          type: integer
          description: Posición dentro del pedido
        comentarios:
          type: string
          description: Información del error funcional
        monto-comision:
          type: number
          description: Comisión de la estación
        comision-flete:
          type: number
          description: Comisión del flete
        descuento:
          type: number
          description: Monto en pesos de descuento
        condicion-precio:
          type: string
          description: Tipo de acuerdo de precio
    problem:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: 'about:blank'
          example: 'https://example.com/probs/out-of-credit'
        title:
          type: string
          description: |
            A short, summary of the problem type. Readable for engineers
            (usually not suited for non technical stakeholders and not localized);
            example: Service Unavailable
          example: You do not have enough credit
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 403
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Your current balance is 30, but that costs 50.
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          example: '/account/12345/msgs/abc'
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
security:
  - api_key: []
tags:
  - name: Tipo
    description: Técnica
  - name: Estado
    description: Diseño
