apiVersion: v1
kind: Secret
metadata:
  name: aws-auth
  namespace: rhi-3scale
  generation: 1
stringData:
  AWS_ACCESS_KEY_ID: <ID_KEY>
  AWS_SECRET_ACCESS_KEY: <ACCESS_KEY>
  AWS_BUCKET: <AWS_S3_NAME>
  AWS_REGION: us-east-2
type: Opaque