{{- range untilStep 1 (int .Values.LastUser) (int .Values.Interval) }}
{{ $n := . }}
---
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    openshift.io/requester: test-user{{$n}}
  name: test-user{{$n}}
{{- end }}